"""
Content Agent

Generates content drafts, suggestions, and repurposing.
LOW autonomy - all outputs require human approval before use.
"""

from datetime import datetime
from typing import Any, Dict, List, Optional
from uuid import uuid4

from app.agents.base import (
    AgentContext,
    AgentResult,
    AgentTask,
    AgentType,
    AutonomyLevel,
    BaseAgent,
    EvidenceItem,
)


class ContentAgent(BaseAgent):
    """
    Content generation agent with LOW autonomy.
    
    All generated content requires human approval before:
    - Publishing
    - Sending to anyone
    - Being used in any external context
    
    Capabilities:
    - Generate content drafts from prompts/topics
    - Repurpose existing content for different platforms
    - Suggest improvements to existing content
    - Generate content ideas
    """

    def __init__(self):
        super().__init__(
            agent_type=AgentType.CONTENT,
            autonomy_level=AutonomyLevel.LOW,
        )

    @property
    def name(self) -> str:
        return "Content Agent"

    @property
    def description(self) -> str:
        return "Generates content drafts and suggestions (requires approval)"

    @property
    def capabilities(self) -> List[str]:
        return [
            "generate_draft",
            "generate_ideas",
            "repurpose_content",
            "suggest_improvements",
            "check_grammar",
            "optimize_seo",
        ]

    async def can_handle(self, task: AgentTask) -> bool:
        """Check if this is a content-related task."""
        content_tasks = {
            "generate_draft",
            "generate_content",
            "generate_ideas",
            "repurpose_content",
            "suggest_improvements",
            "check_grammar",
            "optimize_seo",
        }
        return task.task_type.lower() in content_tasks

    async def execute(
        self,
        task: AgentTask,
        context: AgentContext,
    ) -> AgentResult:
        """Execute content generation task."""
        task_type = task.task_type.lower()

        if task_type in ("generate_draft", "generate_content"):
            return await self._generate_draft(task, context)
        elif task_type == "generate_ideas":
            return await self._generate_ideas(task, context)
        elif task_type == "repurpose_content":
            return await self._repurpose_content(task, context)
        elif task_type == "suggest_improvements":
            return await self._suggest_improvements(task, context)
        else:
            return self._create_error_result(
                action_type=task_type,
                error=f"Unknown content task type: {task_type}",
            )

    async def _generate_draft(
        self,
        task: AgentTask,
        context: AgentContext,
    ) -> AgentResult:
        """Generate a content draft from a topic/prompt."""
        topic = task.inputs.get("topic", "")
        platform = task.inputs.get("platform", "general")
        tone = task.inputs.get("tone", "professional")
        length = task.inputs.get("length", "medium")
        
        if not topic:
            return self._create_error_result(
                action_type="generate_draft",
                error="Topic is required for content generation",
            )

        # In production, this would call an LLM
        # For now, create a structured draft template
        draft = {
            "title": f"Draft: {topic}",
            "content": f"[AI-generated content about '{topic}' for {platform}]\n\n"
                      f"Tone: {tone}\n"
                      f"Target length: {length}\n\n"
                      f"This is a placeholder for LLM-generated content. "
                      f"In production, this would be generated by GPT-4/Claude.",
            "platform": platform,
            "metadata": {
                "generated_at": datetime.utcnow().isoformat(),
                "tone": tone,
                "length": length,
            },
        }

        return self._create_result(
            action_type="generate_draft",
            output=draft,
            output_type="draft",
            confidence=0.85,
            reasoning=f"Generated draft content about '{topic}' optimized for {platform}",
            requires_approval=True,
            approval_reason="Content draft requires review before use",
            evidence=[
                EvidenceItem(
                    source_type="generation",
                    source_name="ContentAgent",
                    data={"topic": topic, "platform": platform},
                    confidence=0.85,
                ),
            ],
        )

    async def _generate_ideas(
        self,
        task: AgentTask,
        context: AgentContext,
    ) -> AgentResult:
        """Generate content ideas for a niche/topic."""
        niche = task.inputs.get("niche", "")
        count = task.inputs.get("count", 5)
        
        # Placeholder ideas
        ideas = [
            {
                "title": f"Content Idea {i+1} for {niche}",
                "description": f"AI-generated idea about {niche}",
                "format": "video" if i % 2 == 0 else "post",
                "difficulty": "medium",
            }
            for i in range(min(count, 10))
        ]

        return self._create_result(
            action_type="generate_ideas",
            output={"ideas": ideas, "niche": niche},
            output_type="ideas",
            confidence=0.80,
            reasoning=f"Generated {len(ideas)} content ideas for niche: {niche}",
            requires_approval=False,  # Ideas don't need approval
            evidence=[
                EvidenceItem(
                    source_type="generation",
                    source_name="ContentAgent",
                    data={"niche": niche, "count": count},
                    confidence=0.80,
                ),
            ],
        )

    async def _repurpose_content(
        self,
        task: AgentTask,
        context: AgentContext,
    ) -> AgentResult:
        """Repurpose content for a different platform."""
        original_content = task.inputs.get("content", "")
        source_platform = task.inputs.get("source_platform", "unknown")
        target_platform = task.inputs.get("target_platform", "")
        
        if not original_content or not target_platform:
            return self._create_error_result(
                action_type="repurpose_content",
                error="Original content and target platform are required",
            )

        # Placeholder repurposed content
        repurposed = {
            "original_platform": source_platform,
            "target_platform": target_platform,
            "content": f"[Repurposed for {target_platform}]\n\n{original_content[:500]}...",
            "adaptations": [
                f"Adjusted format for {target_platform}",
                "Optimized hashtags",
                "Modified length",
            ],
        }

        return self._create_result(
            action_type="repurpose_content",
            output=repurposed,
            output_type="repurposed_draft",
            confidence=0.82,
            reasoning=f"Repurposed content from {source_platform} to {target_platform}",
            requires_approval=True,
            approval_reason="Repurposed content requires review before publishing",
            evidence=[
                EvidenceItem(
                    source_type="repurposing",
                    source_name="ContentAgent",
                    data={
                        "source_platform": source_platform,
                        "target_platform": target_platform,
                    },
                    confidence=0.82,
                ),
            ],
        )

    async def _suggest_improvements(
        self,
        task: AgentTask,
        context: AgentContext,
    ) -> AgentResult:
        """Suggest improvements to existing content."""
        content = task.inputs.get("content", "")
        
        if not content:
            return self._create_error_result(
                action_type="suggest_improvements",
                error="Content is required for improvement suggestions",
            )

        # Placeholder suggestions
        suggestions = [
            {
                "type": "hook",
                "suggestion": "Add a stronger opening hook to capture attention",
                "priority": "high",
            },
            {
                "type": "cta",
                "suggestion": "Include a clear call-to-action at the end",
                "priority": "medium",
            },
            {
                "type": "formatting",
                "suggestion": "Break up long paragraphs for better readability",
                "priority": "low",
            },
        ]

        return self._create_result(
            action_type="suggest_improvements",
            output={"suggestions": suggestions, "content_length": len(content)},
            output_type="suggestions",
            confidence=0.78,
            reasoning="Analyzed content and generated improvement suggestions",
            requires_approval=False,  # Suggestions are read-only
            evidence=[
                EvidenceItem(
                    source_type="analysis",
                    source_name="ContentAgent",
                    data={"content_length": len(content)},
                    confidence=0.78,
                ),
            ],
        )
